# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCoco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCoco

  target 'TestCocoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCocoUITests' do
    # Pods for testing
	pod 'PKHUD', '~> 5.0'
  end

end
